DEFAULT_SNOWFLAKE_USER = 'DE_ASSIGNMENT'
DEFAULT_SNOWFLAKE_PASS = 'Interview10!'
DEFAULT_SNOWFLAKE_ACCOUNT = 'TF36145-DEV_US_EAST_1'
DEFAULT_SNOWFLAKE_WH = 'DE_ASSIGNMENT'
DEFAULT_SNOWFLAKE_DB = 'DE_ASSIGNMENT_DB'
DEFAULT_SNOWFLAKE_SCHEMA = 'PUBLIC'
DEFAULT_SNOWFLAKE_ROLE = "DE_ASSIGNMENT_ROLE"